version: '3'

networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

volumes:
  rabbitmq: {}

services:
  travel-service:
    image: exchange/travel:1.0
    container_name: exchange_travel
    networks:
      srm:
        ipv4_address: 172.32.0.102
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"

  config-server:
    image: exchange/config-server:1.0
    container_name: exchange_configserver
    networks:
      srm:
        ipv4_address: 172.32.0.103
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
    volumes:
      - ./src/config:/usr/local/config-repo

  rabbitmq-exchange:
    image: rabbitmq:3-management
    container_name: rabbitmq_exchange
    networks:
      srm:
        ipv4_address: 172.32.0.104

  service-discovery:
    image: exchange/service-discovery:1.0
    container_name: exchange_servicediscovery
    networks:
      srm:
        ipv4_address: 172.32.0.105
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"

